server:
  port: 8001

spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: slmadmin
    password: 745700yxy
    driverClassName : oracle.jdbc.OracleDriver

  jpa:
    open-in-view: true
    show-sql: true
    format_sql: true
    use_sql_comments: true

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

  data:
    redis:
      repositories:
        enabled: false

  quartz:
    # 将任务等保存化到数据库
    job-store-type: jdbc
    # 程序结束时会等待quartz相关的内容结束
    wait-for-jobs-to-complete-on-shutdown: true
    # QuartzScheduler启动时更新己存在的Job,这样就不用每次修改targetObject后删除qrtz_job_details表对应记录
    overwrite-existing-jobs: true
    # 这里居然是个map，搞得智能提示都没有，佛了
    properties:
      org:
        quartz:
          # scheduler相关
          scheduler:
            # scheduler的实例名
            instanceName: scheduler
            instanceId: AUTO
          # 持久化相关
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 表示数据库中相关表是QRTZ_开头的
            tablePrefix: QRTZ_
            useProperties: false
          # 线程池相关
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            # 线程数
            threadCount: 10
            # 线程优先级
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

token:
  # jwt有效期 2h
  expire_time: 7200000
  # 密钥 必须六位
  secret_key: world