server:
  port: 8001

spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: slmadmin
    password: 745700yxy
    driverClassName : oracle.jdbc.OracleDriver

  jpa:
    open-in-view: true
    show-sql: true
    format_sql: true
    use_sql_comments: true

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

  data:
    redis:
      repositories:
        enabled: false

token:
  # jwt有效期 2h
  expire_time: 7200000
  # 密钥 必须六位
  secret_key: world